<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<PackageReadmeFile>Readme.md</PackageReadmeFile>
		<LangVersion>9.0</LangVersion>
		<Nullable>enable</Nullable>
		<Title>Generate PDF using DSL</Title>
		<PackageId>PdfSharpDslCore</PackageId>
		<Version>2.0.0</Version>
		<Authors>Pierrick Gourlain</Authors>
		<Company></Company>
		<Description>A DSL using TerraPDF to generate PDF</Description>
		<RepositoryUrl>https://github.com/pgourlain/bnf_and_pdf</RepositoryUrl>
		<PackageIcon>Icon.jpg</PackageIcon>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
	</PropertyGroup>

	<ItemGroup>
	  <None Include="..\LICENSE.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Irony" Version="1.5.3" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
		<PackageReference Include="TerraPDF" Version="2.1.0" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\PdfSharpDsl.Language\PdfSharpDsl.Language.csproj" />
	</ItemGroup>
	<ItemGroup>
		<InternalsVisibleTo Include="pdfsharpdslTests" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="Icon.jpg">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	  <None Update="Readme.md">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
