<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<IsPackable>true</IsPackable>
		<LangVersion>8.0</LangVersion>
		<Description>
			Pdf Generation using source generation
		</Description>
		<Version>1.0.2</Version>
		<Authors>Pierrick Gourlain</Authors>
		<Company></Company>
		<RepositoryUrl>https://github.com/pgourlain/bnf_and_pdf</RepositoryUrl>
		<PackageLicenseFile>LICENSE.md</PackageLicenseFile>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<IncludeBuildOutput>false</IncludeBuildOutput>
		<NoPackageAnalysis>true</NoPackageAnalysis>
		<IsRoslynComponent>true</IsRoslynComponent>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Irony" Version="1.5.3" GeneratePathProperty="true" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4" PrivateAssets="all" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" GeneratePathProperty="true" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\LICENSE.md" Pack="true" PackagePath="\" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<!-- Package the generator in the analyzer directory of the nuget package -->
		<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		<None Include="$(MSBuildProjectDirectory)\..\PdfSharpDsl.Language\bin\$(Configuration)\netstandard2.0\PdfSharpDsl.Language.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />

		<!-- Package the Irony dependency alongside the generator assembly -->
		<None Include="$(PKGIrony)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		<None Include="$(PKGMicrosoft_Extensions_Logging_Abstractions)\lib\netstandard2.0\*.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\PdfSharpDsl.Language\PdfSharpDsl.Language.csproj" PrivateAssets="all" GeneratePathProperty="true" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="DrawingGenerator\CSharpDrawer.cs" />
	</ItemGroup>

	<PropertyGroup>
		<GetTargetPathDependsOn>$(GetTargetPathDependsOn);GetDependencyTargetPaths</GetTargetPathDependsOn>
	</PropertyGroup>

	<Target Name="GetDependencyTargetPaths">
		<ItemGroup>
			<TargetPathWithTargetPlatformMoniker Include="$(PKGIrony)\lib\netstandard2.0\*.dll" IncludeRuntimeDependency="false" />
			<TargetPathWithTargetPlatformMoniker Include="$(MSBuildProjectDirectory)\..\PdfSharpDsl.Language\bin\$(Configuration)\$(TargetFramework)\PdfSharpDsl.Language.dll" IncludeRuntimeDependency="false" />
		</ItemGroup>
	</Target>
</Project>
