<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>$(NetStandardTfm)</TargetFramework>
		<IsPackable>false</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Irony" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="PdfSharpDslCore" />
		<InternalsVisibleTo Include="PdfSharpDslCore.Generator" />
		<InternalsVisibleTo Include="pdfsharpdslTests" />
	</ItemGroup>

</Project>
