name: sharppdfdsl Package

on:
  release:
    types: [created]

jobs:  
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:       
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal  
      - name: pack
        run: dotnet pack -c Release
      - name: add publish
        run: dotnet nuget add source --username pgourlain --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/pgourlain/index.json"
      - name: publish package
        run: dotnet nuget push "pdfsharpdsl/bin/Release/*.nupkg" --source "github"
